version: '2'

services:
  pong-api:
    build: pong-api
    image: pong-api:latest
    ports:
      - 8080:8080
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - /data/db:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null
  client:
    build: client
    image: client:latest
    ports:
      - 3001:3001
    links:
      - node
  node:
    build: node
    image: node:latest
    ports:
      - 3000:3000
